sudo: false
language: python

python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'

env:
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x

matrix:
  exclude:
  - python: '2.6'
    env: DJANGO_VERSION=1.7.x
  - python: '2.6'
    env: DJANGO_VERSION=1.8.x
  - python: '3.5'
    env: DJANGO_VERSION=1.6.x
  - python: '3.5'
    env: DJANGO_VERSION=1.7.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install coveralls coverage
  - coverage report
  - coveralls

notifications:
  slack:
    secure: SdXHO4uh796dNBT+shRaavduAbLa+MLxye7ciKc8hBdyHT5zJAxXHlKJtRdAVUaPWe6Va4dM0sSlYiKEQ4Tcju7xnPi/o2An67c3KAhlsyUSFcSr66155l5V64YCtHtm3lYDWNsj2dHP1X1PAKLxG8TGFwLWImstwwjGvoiVuXc=
